
@startuml barAssistant
class Product{

}
class CategoryType {
    - id: number
    - name: string
    - description: string
    - image: string
}

class Category{

}
class Enterprise{
    - id: number
    - name: string
    - address: string
    - phone: string
    - nif: string

}
class ProductType{

}
class Ingredient{

}
class SectionType{
    - id: number
    - name: string
    - description: string
}
class DeviceType{

}
class Device{

}
class User {
  - id: number
  - name: string
  - email: string
  - passwd: string
}
class Section {
  - id: number
  - name: string
  - description: string

}
Note top of Section
    for example: Bar, Kitchen, Terrace, Waiter
end note

class Order{
    - id: number
    - date: Date
    - totalPrice: number
    - status: string
}
class Table{
    - id: number
    - name: string
    - capacity: number
    - status: string
}

class OrderLine{
    - id: number
    - unityPrice: number
}
Note top of OrderLine
    Must have one line per product
end note
class IngredientType{
    - id: number
    - name: string
    - description: string
    - image: string
    - quantity:number
    - customizable: boolean
}
Class ElaborationSequenceType{
    - id: number
    - sectionOrder: number
}
Class ElaborationSequence{
    - id: number
    - sectionOrder: number
}
Class ProductType{
    - id: number
    - name: string
    - description: string
    - sellPrice: number
    - image: string
    - quantity:number
}
ProductType "1"--"*" ElaborationSequenceType
Product "1"--"*" ElaborationSequence
ElaborationSequenceType "*" -- "1" SectionType
ElaborationSequence "*" -- "1" Section
Table "*" -- "1" Enterprise
Product "*"--"*" Section
Section "1"--"*" Device
SectionType "1"--"*" DeviceType
ProductType "*" -- "1" SectionType
Product "*" -- "1" Enterprise


Order "*" -- "1" Table
Order "*" -- "1" User
Order "*" -- "1" Enterprise
OrderLine "*" -- "1" Order
OrderLine "*" -- "1" Product
OrderLine "*" -- "1" Section :CurrentSection
Enterprise "1" -- "*" Section
Enterprise "1" -- "*" User

CategoryType "1"--"*" CategoryType
ProductType "*"--"*" IngredientType
Product "*" -- "*"  Ingredient
Product "*" -- "*" Category : pertany
ProductType "*" -- "*" CategoryType : pertany

Category "*" -- "1" Enterprise
Ingredient "*" -- "1" Enterprise

@enduml
