
@startuml barAssistant
class Product{

}
class CategoryType{
    - id: number
    - name: string
    - description: string
    - image: string
}
class Category{

}
class Enterprise{
    - id: number
    - name: string
    - address: string
    - phone: string
    - email: string
    - nif: string
    - passwd:string

}
class ProductType{


}
class Ingredient{

}
class SectionType{
    - id: number
    - name: string
    - description: string
}
class DeviceType{

}
class Device{

}
class Section {

}
Note top of Section
    for example: Bar, Kitchen, Terrace, Waiter
end note
class Ordre{
    - id: number
    - date: Date
    - totalPrice: number
    - status: string
}
class Table{
    - id: number
    - name: string
    - capacity: number
    - status: string
}
class OrdreLine{
    - id: number
    - quantity: number
    - unityPrice: number
}
class IngredientType{
    - id: number
    - name: string
    - description: string
    - image: string
    - quantity:number
    - customizable: boolean

}
Class ProductType{
    - id: number
    - name: string
    - description: string
    - sellPrice: number
    - image: string
    - quantity:number
}
CategoryType "1"--"*" CategoryType
OrdreLine "1"--"*" Section
Section "1"--"*" Device
SectionType "1"--"*" DeviceType
ProductType "*" -- "1" SectionType
Product "*" -- "1" Enterprise
Product "*" -- "1" Section
Ordre "*" -- "1" Table
Ordre "*" -- "1" Enterprise
OrdreLine "*" -- "1" Ordre
OrdreLine "*" -- "1" Product

ProductType "*"--"*" IngredientType
Product "*" -- "*"  Ingredient
Product "*" -- "*" Category : pertany
ProductType "*" -- "*" CategoryType : pertany
Enterprise "1" -- "*" Section

Category "*" -- "1" Enterprise
Ingredient "*" -- "1" Enterprise


@enduml
