@startuml
title Insertar Producto (Boundary-Control-Entity)
autonumber
actor Administrador as A

box "Sistema"
    participant B as "<<boundary>>\nProductTypeManagement"
    participant C as "<<control>>\nProductService"
    participant E as "<<entity>>\nProduct"
end box

A -> B: Rellenar datos y Clicar Guardar
B -> C: crearProducto(data)

activate C

    C -> C: validarDatos()
    C -> E: insertarProducto(data)

    activate E

    E --> C: Producto
    deactivate E

    C --> B: Confirmación de éxito(Producto)
deactivate C

B --> A: Mostrar Mensaje de éxito con el Producto
@enduml